Repository weltenwort/home-assistant-rct-power-integration, pull requests merged in 2022-05, with the labels that each got.

#210 Bump dependency versions
  custom_components/rct_power/translations/en.json
  poetry.lock
  pyproject.toml
  requirements_dev.txt
Labels: dependencies

#209 Use native_unit_of_measurement to prevent recursion.
  custom_components/rct_power/lib/entity.py
Labels: bug, patch version

#218 Remove extra manifest entries
  hacs.json
Labels: patch version
