Repository weltenwort/home-assistant-rct-power-integration, pull requests merged in 2023-04, with the labels that each got.

#297 Fix manifest linting error
  custom_components/rct_power/manifest.json
Labels: ci

#302 Remove unused constraints file
  .github/workflows/constraints.txt
Labels: ci, github_actions

#304 fix long-dead legacy links
  custom_components/rct_power/__init__.py
  custom_components/rct_power/lib/const.py
  custom_components/rct_power/translations/en.json
Labels: documentation
