Repository weltenwort/home-assistant-rct-power-integration, pull requests merged in 2024-01, with the labels that each got.

#336 Replace deprecated constants with enums
  custom_components/rct_power/lib/device_class_helpers.py
Labels: bug, python

#337 Avoid caching of late properties
  custom_components/rct_power/lib/entity.py
Labels: bug, python

#339 Fix missing names and name derivation
  .devcontainer/devcontainer.json
  custom_components/rct_power/lib/entities.py
  custom_components/rct_power/lib/entity.py
Labels: enhancement, python

#346 Use python version from project file in workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/tests.yaml
Labels: build, ci

#349 Add entities for battery status
  README.md
  custom_components/rct_power/lib/const.py
  custom_components/rct_power/lib/entities.py
  custom_components/rct_power/lib/entity.py
  custom_components/rct_power/lib/state_helpers.py
  custom_components/rct_power/sensor.py
  poetry.lock
  pyproject.toml
  requirements_dev.txt
Labels: python, minor version

#351 Add separate dis-/charging battery status
  custom_components/rct_power/lib/state_helpers.py
Labels: enhancement, python, minor version

#352 Add battery actuator temperature
  README.md
  custom_components/rct_power/lib/entities.py
  info.md
Labels: enhancement

#353 Add more battery sensors
  README.md
  custom_components/rct_power/lib/entities.py
  custom_components/rct_power/lib/state_helpers.py
  hacs.json
  info.md
  pyproject.toml
  setup.cfg
Labels: enhancement, python, minor version

#354 Speed up CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: ci

#355 Enable unit tests in GitHub workflows
  .github/workflows/tests.yaml
  .vscode/launch.json
  conftest.py
  custom_components/rct_power/__init__.py
  custom_components/rct_power/init_test.py
  poetry.lock
  pyproject.toml
Labels: ci, testing

#356 Set min/max soc entity unit to percent
  custom_components/rct_power/lib/entities.py
Labels: bug, python, patch version

#357 Improve release automation
  .github/labels.yml
  .github/release.yml
  .github/workflows/bump-and-tag-version.yml
Labels: ci
